var gmap=null,overlay,MY_MAPTYPE_ID="gray",bounds,dialog,markersArray=[],lastID=null,dataAll,Itinerary,directionDisplay,directionsService=new google.maps.DirectionsService,origin=null,destination=null,waypoints=[],markers=[],directionsVisible=!1,imageRed=new google.maps.MarkerImage("images/mapIcons/red.png",new google.maps.Size(12,20),new google.maps.Point(0,0),new google.maps.Point(0,20)),imageYellow=new google.maps.MarkerImage("images/mapIcons/yellow.png",new google.maps.Size(12,20),new google.maps.Point(0,
0),new google.maps.Point(0,20)),imageGreen=new google.maps.MarkerImage("images/mapIcons/green.png",new google.maps.Size(12,20),new google.maps.Point(0,0),new google.maps.Point(0,20)),shadow=new google.maps.MarkerImage("images/mapIcons/mm_20_shadow.png",new google.maps.Size(22,20),new google.maps.Point(0,0),new google.maps.Point(0,20)),shape={coord:[1,1,1,20,18,20,18,1],type:"poly"},imageOver=new google.maps.MarkerImage("images/mapIcons/highlight.png",new google.maps.Size(12,20),new google.maps.Point(0,
0),new google.maps.Point(0,20)),myMarker=!1;
function initialize(){new dijit.form.Button({label:"Reset",title:"Reset search criteria",type:"reset",onClick:function(){clearSearchBox();queryData(1)}},"buttonReset");new dijit.form.Button({label:"Get Directions!",onClick:function(){reset();calcRoute()}},"buttonDirections");new dijit.form.Button({label:"Reset",onClick:function(){reset();destroyAll()}},"buttonRemove");new dijit.form.Button({label:"Delete selected Site(s)",onClick:function(){deleteSelected()}},"buttonDelete");var a={zoom:12,center:new google.maps.LatLng(47.250138520439556,
-122.47643585205077),panControl:!1,zoomControl:!0,zoomControlOptions:{style:google.maps.ZoomControlStyle.SMALL,position:google.maps.ControlPosition.RIGHT_TOP},mapTypeControl:!0,mapTypeControlOptions:{mapTypeIds:[MY_MAPTYPE_ID,google.maps.MapTypeId.HYBRID]},scaleControl:!0,streetViewControl:!0,overviewMapControl:!1,mapTypeId:MY_MAPTYPE_ID};gmap=new google.maps.Map(document.getElementById("map_canvas"),a);a=new google.maps.StyledMapType([{featureType:"administrative",elementType:"all",stylers:[{saturation:-100}]},
{featureType:"landscape",elementType:"all",stylers:[{saturation:-100}]},{featureType:"poi",elementType:"all",stylers:[{saturation:-100}]},{featureType:"road",elementType:"all",stylers:[{saturation:-100}]},{featureType:"transit",elementType:"all",stylers:[{saturation:-100}]},{featureType:"water",elementType:"all",stylers:[{saturation:-100}]}],{name:"Map",alt:"Show standard map"});gmap.mapTypes.set(MY_MAPTYPE_ID,a);a=document.createElement("DIV");a.style.padding="5px 5px 5px 5px";var b=document.createElement("DIV");
b.style.backgroundColor="#77C9B2";b.style.borderStyle="solid";b.style.borderWidth="2px";b.style.borderColor="#b2b2b2";var d=document.createElement("img");d.src="images/legend.jpg";d.style.width="69px";d.style.height="39px";b.appendChild(d);a.appendChild(b);gmap.controls[google.maps.ControlPosition.LEFT_TOP].push(a);a=document.createElement("DIV");a.style.padding="0px 10px 5px 5px";b=document.createElement("DIV");b.style.backgroundColor="rgba(102,102,102,0.80)";b.style.borderStyle="solid";b.style.borderWidth=
"1px";b.style.borderRadius="2px";b.style.borderColor="#D2D4D7";b.style.cursor="pointer";b.style.width="38px";b.style.height="38px";d=document.createElement("img");d.src="images/homeWhite2.png";d.style.width="32px";d.style.height="32px";d.style.margin="3px 0px 0px 3px";d.title="Zoom to Selected Art";b.appendChild(d);a.appendChild(b);gmap.controls[google.maps.ControlPosition.RIGHT_TOP].push(a);google.maps.event.addDomListener(b,"click",function(){gmap.fitBounds(bounds)});overlay=new google.maps.OverlayView;
overlay.draw=function(){};overlay.setMap(gmap);dojo.byId("theItinerary1").innerHTML="<div><b>Create your own itinerary:</b><ul><li>Enter Starting Point information</li><li>Click map marker</li><li>Select <i>Add to my Itinerary</i> <br>(up to 9 sites)</li></ul></div><div style='border-top:1px solid #C0C0C0;background:#EEEEEE;padding:4px 4px 4px 4px;'><b>Starting Point:</b></div><div style='float:right;'>Address: <input type='text' name='StartAddress1' id='StartAddress1' value='747 Market St' /></div><div style='float:right;'>City: <input type='text' name='StartAddress2' id='StartAddress2' value='Tacoma' /><br />&nbsp;</div><div style='clear:both;background:#EEEEEE;padding:4px 4px 4px 4px;'><b>Itinerary: </b></div><div class='Itinerary Container' style='clear:both;width:230px;'><ol id='Itinerary Node' class='container'></ol></div>";
dojo.byId("theItinerary2").innerHTML="<i>No Sites selected.</i>";dojo.byId("directions1").innerHTML="<a href='javascript:PrintContent();'>Print Directions</a>";dojo.byId("directions2").innerHTML="<a href=\"javascript:togglePane('rightPane','rightTabs','ItineraryTab');\">Modify Itinerary</a>";dojo.byId("headerContent").innerHTML="<div style='float:left;color:rgb(0,0,0); font-weight:bold;'>Tacoma-Pierce County Public Art Tour</div><div style=\"float:right;\"><input type=\"text\"  title='Search for title or artist by keyword' name='theKeywords' id='theKeywords' value=' Search by title or artist...' onmouseover=\"if (this.value==' Search by title or artist...') this.value = ''\" onmouseout=\"if (this.value=='')this.value=' Search by title or artist...';\" onkeypress=\"if(event.keyCode==13) {newKeyQuery();}\" style=\"background: white url(images/search.png) right no-repeat;padding-right: 17px;\"/></div><div style='float:right;'><a href='#' onclick=\"javascript:dijit.byId('mapWelcome').show();\" style='color:#EEEEEE; font-weight:bold;'>Welcome - Contact Us</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </div>";
Itinerary=new dojo.dnd.Source("Itinerary Node");Itinerary.insertNodes(!1,[]);dojo.dnd.Avatar.prototype._generateText=function(){return this.manager.copy?"copy":"Move to here"};directionsDisplay=new google.maps.DirectionsRenderer;directionsDisplay.setMap(gmap);directionsDisplay.setPanel(document.getElementById("directionsPanel"));bounds=new google.maps.LatLngBounds}
function addMarker(a,b,d,e,h,c,g){a=new google.maps.LatLng(a,b);var f=new google.maps.Marker({position:a,id:g,shadow:shadow,icon:c,shape:shape,optimized:!1,map:gmap});google.maps.event.addListener(f,"mouseover",function(){f.setIcon(imageOver);var a=f.getPosition();a=overlay.getProjection().fromLatLngToContainerPixel(a);closeDialog();var b=new dijit.TooltipDialog({id:"tooltipDialog",content:d,style:"position: absolute;z-index:100"});b.startup();dojo.style(b.domNode,"opacity",.85);dijit.placeOnScreen(b.domNode,
{x:a.x,y:a.y},["BL","TL","BR","TR"],{x:25,y:15})});google.maps.event.addListener(f,"mouseout",function(){f.setIcon(c);closeDialog()});google.maps.event.addListener(f,"click",function(){myDialog(e,h)});markersArray.push(f)}function closeDialog(){var a=dijit.byId("tooltipDialog");a&&a.destroy()}function myDialog(a,b){myDlg=new dijit.Dialog({draggable:!1});myDlg.titleNode.innerHTML=b;myDlg.attr("content",a);myDlg.show();dojo.connect(dijit._underlay,"onClick",function(a){myDlg.destroy()})}
function myLightbox(a,b){dialog.show({href:a,title:b})}
function calcRoute(){directionsDisplay.setPanel(document.getElementById("directionsPanel"));origin=dojo.byId("StartAddress1").value+","+dojo.byId("StartAddress2").value;var a=dojo.byId("Itinerary Node").getElementsByTagName("li");for(i=0;i<a.length;i++)destination=a[i].innerHTML+",WA",i+1!=a.length&&waypoints.push({location:destination,stopover:!0});var b={origin:origin,destination:destination,waypoints:waypoints,travelMode:google.maps.DirectionsTravelMode.DRIVING,optimizeWaypoints:document.getElementById("optimize").checked};
0==a.length?alert("No Sites in Itinerary."):""==dojo.byId("StartAddress1").value?alert("Please enter a Starting Point Address."):(directionsService.route(b,function(a,b){b==google.maps.DirectionsStatus.OK&&(directionsDisplay.setDirections(a),togglePane("rightPane","rightTabs","DirectionsTab"))}),clearMarkers(),directionsVisible=!0)}function clearMarkers(){for(var a=0;a<markers.length;a++)markers[a].setMap(null)}
function clearWaypoints(){markers=[];destination=origin=null;waypoints=[];directionsVisible=!1}function reset(){clearMarkers();clearWaypoints();directionsDisplay.setMap(null);directionsDisplay.setPanel(null);directionsDisplay=new google.maps.DirectionsRenderer;directionsDisplay.setMap(gmap);directionsDisplay.setPanel(document.getElementById("theDirections"))}function clearSearchBox(){document.getElementById("theKeywords").value=" Search by title or artist..."}
function togglePane(a,b,d){dijit.byId(a)._showing?dijit.byId(b).selectedChildWidget.id!=d?dijit.byId(b).selectChild(d):dijit.byId(a).toggle():dijit.byId(b).selectChild(d)}function destroyAll(){dojo.empty("Itinerary Node");dojo.byId("theItinerary2").style.display="block";dojo.byId("theItinerary3").style.display="none";dojo.byId("theItinerary4").style.display="none"}
function addStudio(a){var b="No",d=dojo.byId("Itinerary Node").getElementsByTagName("li");if(9==d.length)alert("Itinerary limited to 9 Sites.  Please remove a Site from Itinerary before adding additional Sites.");else{for(i=0;i<d.length;i++)d[i].innerHTML==a&&(b="Yes");"No"==b&&Itinerary.insertNodes(!1,[a])}dojo.byId("theItinerary2").style.display="block";dojo.byId("theItinerary2").style.display="none";dojo.byId("theItinerary3").style.display="block";dojo.byId("theItinerary4").style.display="block"}
function deleteSelected(){Itinerary.deleteSelectedNodes()}function PrintContent(){var a=document.getElementById("directionsPanel"),b=window.open("","PrintWindow","width=750,height=650,top=50,left=50,toolbars=no,scrollbars=yes,status=no,resizable=yes");b.document.writeln(a.innerHTML);b.document.close();b.focus();b.print()}function queryData(a){cleanMap();bounds=new google.maps.LatLngBounds;1==a?newQuery(1):newQuery()}
function cleanMap(){if(markersArray){for(i in markersArray)markersArray[i].setMap(null);markersArray=[]}}function getJson(){dojo.xhrGet({url:"PubArt.txt",handleAs:"json",preventCache:!0,load:load_handler,error:error_handler})}function load_handler(a){dataAll=a;a=dojox.json.query("$.items[/Title]",dataAll);addMarkers(a)}function error_handler(a){alert("--- Error occurred. ---\n "+error.message)}
function newQuery(a){closeDialog();var b="$.items[";1!=a&&("All"!=dijit.byId("Category").value&&(b="Mural"==dijit.byId("Category").value?b+("?Category ='"+dijit.byId("Category").value+"' "):"Sculpture"==dijit.byId("Category").value?b+"?Category ='Sculpture*' ":b+"?Category !='Mural' & Category !='Sculpture: Outdoor' & Category !='Sculpture, Outdoor' & Category !='Sculpture, Indoor' & Category !='Sculpture' & Category !='Sculpture Indoor' & Category !='Sculpture: Indoor' "),"All"!=dijit.byId("Location").value&&
(b=8<b.length?b+(" & Neighborhood ='"+dijit.byId("Location").value+"' "):b+("?Neighborhood ='"+dijit.byId("Location").value+"' ")),"All"!=dijit.byId("Artist").value&&(b=8<b.length?b+(" & Artist ='"+dijit.byId("Artist").value+"' "):b+("?Artist ='"+dijit.byId("Artist").value+"' ")));b=8==b.length?"$.items[/Title]":b+"][/Title]";a=dojox.json.query(b,dataAll);0==a.length?(alert("Sorry, no art found. Please modify search."),b="<i>No artwork found</i>",dojo.byId("searchResults").innerHTML=""):(b=1==a.length?
"<i>One artwork found</i>":"<i>"+a.length+" artworks found</i>",addMarkers(a));dojo.byId("artCount").innerHTML=b}
function newKeyQuery(){cleanMap();bounds=new google.maps.LatLngBounds;closeDialog();var a=("*"+document.getElementById("theKeywords").value+"*").replace("'","\\'");a=dojox.json.query("$.items[?Artist~'"+a+"' || Title~'"+a+"'][/Title]",dataAll);if(0==a.length){alert("Sorry, no art found. Please modify search.");var b="<i>No artwork found</i>";dojo.byId("searchResults").innerHTML=""}else b=1==a.length?"<i>One artwork found</i>":"<i>"+a.length+" artworks found</i><br> for keyword = "+document.getElementById("theKeywords").value,
addMarkers(a);dojo.byId("artCount").innerHTML=b}
function addMarkers(a){for(var b=0,d,e,h="",c=0;c<a.length;c++){if(null!=a[c].Lat){e=d="";d+="<div style='color:rgb(56,64,142); font-weight:bold; font-style:italic; text-align:center; '>"+a[c].Title+"</div>";d+="<div style=\"text-align:center;\"><div style='text-align:center; max-width: 260px;'><b>"+a[c].Artist+"</b></div>";var g="images/artwork/"+a[c].Image,f=g.replace(".JPG","1.JPG").replace(".jpg","1.jpg");d+="<br><a href=\"javascript:myLightbox('"+g+"','"+a[c].Artist.replace(/'/g,"\\'")+": <i>"+
a[c].Title.replace(/'/g,"\\'")+'</i>\')"><img src="'+f+'" style="max-width:100px;max-height:100px;margin:2px 5px 5px 0px;border:solid 1px #999;padding:2px"  title=\'Click to enlarge photo\'/></a>';d+="<br><i>Click marker for details</i></div>";var l="<span style='color:rgb(56,64,142);'>"+a[c].Title+"</span>";e+="<div style='clear:both;float:left;width: 260px;'>";var k=a[c].Location1+", "+a[c].City;e+="<div style='clear:both;'>";e+="<span style='color:rgb(56,64,142);'>"+k+"</span>";e+='<br><a href="https://maps.google.com/maps?daddr='+
k+", WA\" target='_blank'>Directions</a>";e+="&nbsp;|&nbsp;<a href='javascript:go2art("+a[c].Lat+", "+a[c].Long+")' title='Close this window and zoom map to Studio.'>Zoom</a>";e+='&nbsp;|&nbsp;<a href="https://maps.google.com/?cbll='+a[c].Lat+","+a[c].Long+"&cbp=13,0,,,&layer=c&z=17\" target='_blank'>Street View</a><br>";e+="<span style=clear:both;float:right;'><b>Add to my Itinerary?</b> <input type='radio' name='Itinerary' id='y' onclick='addStudio(\""+k+'");togglePane("rightPane","rightTabs","ItineraryTab");\'/>Yes</span><br>';
e+="</div>";e+="<div style='clear:both;'><hr color='#ACB1DB'></div>";e+="<div style='clear:both;float:left;width:200px;'>";e+="<a href=\"javascript:myLightbox('"+g+"','"+a[c].Artist.replace(/'/g,"\\'")+": <i>"+a[c].Title+"</i>')\"><img style ='float:left;margin:2px 5px 5px 5px;border:solid 1px #999;padding:2px' src='"+f+"' title='Click to enlarge photo' max-height='100px' max-width='100px'></a>";e+="</div>";e+="<div style='width: 240px;float:left;'>";e+="<b>"+a[c].Artist;e+="</b><br>";e+="<span style='color:rgb(56,64,142);'><I>Category: </span>"+
a[c].Category+"</I><br>";""!=a[c].Medium&&(e+="<span style='color:rgb(56,64,142);'><I>Medium: </span>"+a[c].Medium+"</I><br>");""!=a[c].Dimensions&&(e+="<span style='color:rgb(56,64,142);'><I>Dimensions: </span>"+a[c].Dimensions+"</I><br>");""!=a[c].Year&&(e+="<span style='color:rgb(56,64,142);'><I>Year Created: </span>"+a[c].Year+"</I><br>");""!=a[c].Location2&&(e+="<span style='color:rgb(56,64,142);'><I>Location: </span>"+a[c].Location2+"</I><br>");""!=a[c].Agency&&(e+="<span style='color:rgb(56,64,142);'><I>Agency: </span>"+
a[c].Agency+"</I><br>");e+="<p>"+a[c].Description+"</p>";e+="</div>";g=imageGreen;"Sculpture"==a[c].Category.substr(0,9)?g=imageRed:"Mural"==a[c].Category&&(g=imageYellow);addMarker(a[c].Lat,a[c].Long,d,e,l,g);h+=d.replace("Click marker for details","");h+="<center><b><a title='Zoom map to artwork and highlight' href='javascript:go2art("+a[c].Lat+", "+a[c].Long+","+b+")'>Zoom</a>  |";h+="  <a title='Complete artwork details' href='javascript:myBlur();closeDialog();google.maps.event.trigger(markersArray["+
b+'],"click")\'>Details</a>  |';h+="  <a title='Back to top of page' href='#dataQuery'>Back to Top</a></b></center>";h+="<div style='clear:both;'><hr color='#ACB1DB'></div>";bounds.extend(new google.maps.LatLng(a[c].Lat,a[c].Long));c+1==a.length&&(gmap.fitBounds(bounds),17<gmap.getZoom()&&(gmap.setZoom(17),gmap.setCenter(bounds.getCenter())))}b+=1}dojo.byId("searchResults").innerHTML=h}function myBlur(){document.getElementById("theKeywords").focus()}
function go2art(a,b,d){"undefined"!==typeof myDlg&&myDlg.destroy();null!=lastID&&google.maps.event.trigger(markersArray[lastID],"mouseout");var e=new google.maps.LatLngBounds;a=new google.maps.LatLng(a,b);e.extend(a);gmap.setZoom(17);gmap.setCenter(e.getCenter());lastID=d;setTimeout(function(){google.maps.event.trigger(markersArray[d],"mouseover")},500)}
require("dojo/parser dijit/layout/BorderContainer dijit/layout/TabContainer dijit/layout/ContentPane dijit/form/Form dijit/form/Button dijit/form/FilteringSelect dojox/json/query dojox/image/Lightbox dijit/Dialog dijit/TooltipDialog dojo/dnd/Source dojo/domReady!".split(" "),function(a){a.parse();initialize();getJson();dialog=(new dojox.image.LightboxDialog).startup();dijit.byId("mapWelcome").show()});